//go:build !ignore_autogenerated

/*
Copyright 2024 OCP Guardian.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	rbacv1 "k8s.io/api/rbac/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateExpiryMonitor) DeepCopyInto(out *CertificateExpiryMonitor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateExpiryMonitor.
func (in *CertificateExpiryMonitor) DeepCopy() *CertificateExpiryMonitor {
	if in == nil {
		return nil
	}
	out := new(CertificateExpiryMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertificateExpiryMonitor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateExpiryMonitorList) DeepCopyInto(out *CertificateExpiryMonitorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CertificateExpiryMonitor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateExpiryMonitorList.
func (in *CertificateExpiryMonitorList) DeepCopy() *CertificateExpiryMonitorList {
	if in == nil {
		return nil
	}
	out := new(CertificateExpiryMonitorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertificateExpiryMonitorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateExpiryMonitorSpec) DeepCopyInto(out *CertificateExpiryMonitorSpec) {
	*out = *in
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ExcludeNamespaces != nil {
		in, out := &in.ExcludeNamespaces, &out.ExcludeNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateExpiryMonitorSpec.
func (in *CertificateExpiryMonitorSpec) DeepCopy() *CertificateExpiryMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(CertificateExpiryMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateExpiryMonitorStatus) DeepCopyInto(out *CertificateExpiryMonitorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExpiringCertificates != nil {
		in, out := &in.ExpiringCertificates, &out.ExpiringCertificates
		*out = make([]CertificateInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastScanTime != nil {
		in, out := &in.LastScanTime, &out.LastScanTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateExpiryMonitorStatus.
func (in *CertificateExpiryMonitorStatus) DeepCopy() *CertificateExpiryMonitorStatus {
	if in == nil {
		return nil
	}
	out := new(CertificateExpiryMonitorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateInfo) DeepCopyInto(out *CertificateInfo) {
	*out = *in
	in.ExpiryDate.DeepCopyInto(&out.ExpiryDate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateInfo.
func (in *CertificateInfo) DeepCopy() *CertificateInfo {
	if in == nil {
		return nil
	}
	out := new(CertificateInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterDegradationMonitor) DeepCopyInto(out *ClusterDegradationMonitor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterDegradationMonitor.
func (in *ClusterDegradationMonitor) DeepCopy() *ClusterDegradationMonitor {
	if in == nil {
		return nil
	}
	out := new(ClusterDegradationMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterDegradationMonitor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterDegradationMonitorList) DeepCopyInto(out *ClusterDegradationMonitorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterDegradationMonitor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterDegradationMonitorList.
func (in *ClusterDegradationMonitorList) DeepCopy() *ClusterDegradationMonitorList {
	if in == nil {
		return nil
	}
	out := new(ClusterDegradationMonitorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterDegradationMonitorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterDegradationMonitorSpec) DeepCopyInto(out *ClusterDegradationMonitorSpec) {
	*out = *in
	if in.OperatorFilter != nil {
		in, out := &in.OperatorFilter, &out.OperatorFilter
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterDegradationMonitorSpec.
func (in *ClusterDegradationMonitorSpec) DeepCopy() *ClusterDegradationMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterDegradationMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterDegradationMonitorStatus) DeepCopyInto(out *ClusterDegradationMonitorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ClusterOperators != nil {
		in, out := &in.ClusterOperators, &out.ClusterOperators
		*out = make([]ClusterOperatorHealth, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastCorrelationTime != nil {
		in, out := &in.LastCorrelationTime, &out.LastCorrelationTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterDegradationMonitorStatus.
func (in *ClusterDegradationMonitorStatus) DeepCopy() *ClusterDegradationMonitorStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterDegradationMonitorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterOperatorHealth) DeepCopyInto(out *ClusterOperatorHealth) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterOperatorHealth.
func (in *ClusterOperatorHealth) DeepCopy() *ClusterOperatorHealth {
	if in == nil {
		return nil
	}
	out := new(ClusterOperatorHealth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRoleBaseline) DeepCopyInto(out *ClusterRoleBaseline) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]rbacv1.PolicyRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRoleBaseline.
func (in *ClusterRoleBaseline) DeepCopy() *ClusterRoleBaseline {
	if in == nil {
		return nil
	}
	out := new(ClusterRoleBaseline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRoleBindingBaseline) DeepCopyInto(out *ClusterRoleBindingBaseline) {
	*out = *in
	out.RoleRef = in.RoleRef
	if in.Subjects != nil {
		in, out := &in.Subjects, &out.Subjects
		*out = make([]rbacv1.Subject, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRoleBindingBaseline.
func (in *ClusterRoleBindingBaseline) DeepCopy() *ClusterRoleBindingBaseline {
	if in == nil {
		return nil
	}
	out := new(ClusterRoleBindingBaseline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBACBaseline) DeepCopyInto(out *RBACBaseline) {
	*out = *in
	if in.ClusterRoles != nil {
		in, out := &in.ClusterRoles, &out.ClusterRoles
		*out = make([]ClusterRoleBaseline, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ClusterRoleBindings != nil {
		in, out := &in.ClusterRoleBindings, &out.ClusterRoleBindings
		*out = make([]ClusterRoleBindingBaseline, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]RoleBaseline, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RoleBindings != nil {
		in, out := &in.RoleBindings, &out.RoleBindings
		*out = make([]RoleBindingBaseline, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBACBaseline.
func (in *RBACBaseline) DeepCopy() *RBACBaseline {
	if in == nil {
		return nil
	}
	out := new(RBACBaseline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBACDrift) DeepCopyInto(out *RBACDrift) {
	*out = *in
	in.DetectedAt.DeepCopyInto(&out.DetectedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBACDrift.
func (in *RBACDrift) DeepCopy() *RBACDrift {
	if in == nil {
		return nil
	}
	out := new(RBACDrift)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBACDriftMonitor) DeepCopyInto(out *RBACDriftMonitor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBACDriftMonitor.
func (in *RBACDriftMonitor) DeepCopy() *RBACDriftMonitor {
	if in == nil {
		return nil
	}
	out := new(RBACDriftMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RBACDriftMonitor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBACDriftMonitorList) DeepCopyInto(out *RBACDriftMonitorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RBACDriftMonitor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBACDriftMonitorList.
func (in *RBACDriftMonitorList) DeepCopy() *RBACDriftMonitorList {
	if in == nil {
		return nil
	}
	out := new(RBACDriftMonitorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RBACDriftMonitorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBACDriftMonitorSpec) DeepCopyInto(out *RBACDriftMonitorSpec) {
	*out = *in
	in.Baseline.DeepCopyInto(&out.Baseline)
	if in.ExcludePatterns != nil {
		in, out := &in.ExcludePatterns, &out.ExcludePatterns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeAnnotations != nil {
		in, out := &in.ExcludeAnnotations, &out.ExcludeAnnotations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBACDriftMonitorSpec.
func (in *RBACDriftMonitorSpec) DeepCopy() *RBACDriftMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(RBACDriftMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBACDriftMonitorStatus) DeepCopyInto(out *RBACDriftMonitorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DriftItems != nil {
		in, out := &in.DriftItems, &out.DriftItems
		*out = make([]RBACDrift, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastCheckTime != nil {
		in, out := &in.LastCheckTime, &out.LastCheckTime
		*out = (*in).DeepCopy()
	}
	if in.SnapShotBaseline != nil {
		in, out := &in.SnapShotBaseline, &out.SnapShotBaseline
		*out = new(RBACBaseline)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBACDriftMonitorStatus.
func (in *RBACDriftMonitorStatus) DeepCopy() *RBACDriftMonitorStatus {
	if in == nil {
		return nil
	}
	out := new(RBACDriftMonitorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleBaseline) DeepCopyInto(out *RoleBaseline) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]rbacv1.PolicyRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleBaseline.
func (in *RoleBaseline) DeepCopy() *RoleBaseline {
	if in == nil {
		return nil
	}
	out := new(RoleBaseline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleBindingBaseline) DeepCopyInto(out *RoleBindingBaseline) {
	*out = *in
	out.RoleRef = in.RoleRef
	if in.Subjects != nil {
		in, out := &in.Subjects, &out.Subjects
		*out = make([]rbacv1.Subject, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleBindingBaseline.
func (in *RoleBindingBaseline) DeepCopy() *RoleBindingBaseline {
	if in == nil {
		return nil
	}
	out := new(RoleBindingBaseline)
	in.DeepCopyInto(out)
	return out
}
